({
  Entity: {},
  /* Metarhia does not support UUID for primary key.
    That's intentional decision due to performance concerns.
    So in the case of UUID needed you must declare separate field (e.g. `guid`)
    to hold generated identifier and mark it as unique. */

  /**
   * Universally unique identifier for cross-system or public communication about the entity.
   * Used as a separate ID key only!
   * All internal entity references uses primary generated as identity key of type BigInt.
   */
  guid: {
    // Custom type: autogenerated by Postgres UUID
    type: 'genUUID',
    unique: true,
  },
  client: { type: 'Client', delete: 'cascade' },
  cardNo: {
    // Custom string type with validation pattern
    type: 'cardNumber',
  },
  main: { type: '?boolean', default: false },
});
