({
  Entity: {
    note: 'A parking for electric vehicles',
  },
  /* Metarhia does not support UUID for primary key.
    That's intentional decision due to performance concerns.
    So in the case of UUID needed you must declare separate field (e.g. `guid`)
    to hold generated identifier and mark it as unique. */

  /**
   * Universally unique identifier for cross-system or public communication about the entity.
   * Used as a separate ID key only!
   * All internal entity references uses primary generated as identity key of type BigInt.
   */
  guid: {
    /** Custom type: autogenerated by Postgres UUID */
    type: 'genUUID',
    unique: true,
  },
  name: 'string',
  // Custom types to describe domain models that not entity to be stored as JSONB in DB
  address: 'addressObject',
  location: 'locationObject',
  // TODO: How to describe one-to-many relation at the "one" side?
  // spots: { many: 'Spot' },  // <-- this creates many-to-many
  // chargers: { many: 'ElectricCharger' }, // <-- this creates many-to-many
});
