({
  Entity: {
    note: 'An electric vehicle model',
  },
  /* Metarhia does not support UUID for primary key.
    That's intentional decision due to performance concerns.
    So in the case of UUID needed you must declare separate field (e.g. `guid`)
    to hold generated identifier and mark it as unique. */

  /**
   * Universally unique identifier for cross-system or public communication about the entity.
   * Used as a separate ID key only!
   * All internal entity references uses primary generated as identity key of type BigInt.
   */
  guid: {
    /** Custom type: autogenerated by Postgres UUID */
    type: 'genUUID',
    unique: true,
  },
  model: { type: 'string', unique: true },
  kind: {
    enum: ['bicycle', 'scooter', 'motorcycle', 'car', 'van', 'truck', 'bus'],
    note: 'A kind of a vehicle',
    length: { max: 32 },
  },
  portType: 'PortType',
});
